// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDv3piDreRRWEgreZrJPnDLbIP68UUzc0',
    appId: '1:158250044081:android:6d059bc642dca87709f090',
    messagingSenderId: '158250044081',
    projectId: 'srvice-guide',
    storageBucket: 'srvice-guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYa4MfO_427SlsR-9DoeXM1Bfo8aNT6NU',
    appId: '1:158250044081:ios:067c2e96c9d036e009f090',
    messagingSenderId: '158250044081',
    projectId: 'srvice-guide',
    storageBucket: 'srvice-guide.appspot.com',
    iosBundleId: 'com.example.servicesGuide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraqPCylvZvwYWLl_DRaofa269PnfZ06U',
    appId: '1:158250044081:web:f7f422f5eeb5daa709f090',
    messagingSenderId: '158250044081',
    projectId: 'srvice-guide',
    authDomain: 'srvice-guide.firebaseapp.com',
    storageBucket: 'srvice-guide.appspot.com',
    measurementId: 'G-KL5L3CP5DD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYa4MfO_427SlsR-9DoeXM1Bfo8aNT6NU',
    appId: '1:158250044081:ios:067c2e96c9d036e009f090',
    messagingSenderId: '158250044081',
    projectId: 'srvice-guide',
    storageBucket: 'srvice-guide.appspot.com',
    iosBundleId: 'com.example.servicesGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCraqPCylvZvwYWLl_DRaofa269PnfZ06U',
    appId: '1:158250044081:web:eb6ddb466f07962f09f090',
    messagingSenderId: '158250044081',
    projectId: 'srvice-guide',
    authDomain: 'srvice-guide.firebaseapp.com',
    storageBucket: 'srvice-guide.appspot.com',
    measurementId: 'G-7NE4YNWECY',
  );

}